### ISSUE TITLE
Vulnerability in 3.9.2

### ISSUE THREAD

**Issue by alexincore** [wp-stream/stream#1426]
# Feature Request / Question

Patchstack reported version 3.9.2 as being vulnerable to CSRF 
[https://patchstack.com/database/vulnerability/stream/wordpress-stream-plugin-3-9-2-cross-site-request-forgery-csrf-vulnerability?_a_id=431](https://patchstack.com/database/vulnerability/stream/wordpress-stream-plugin-3-9-2-cross-site-request-forgery-csrf-vulnerability?_a_id=431)

Any chance you have it in your queue?

**Comment by kasparsd** [comment]
Thanks for reporting this! We received the first report of the issue only a few hours ago and are looking into this.

**Comment by Japh** [comment]
Do we know when this fix will be released onto the WP.org plugin repo? Thanks for fixing it!

**Comment by mustafauysal** [comment]
It appears to be available on .org now! Thanks for the fix! 👍🏼
