### ISSUE TITLE
Add reset button to reset all filters

### ISSUE THREAD

**Issue by jonathanbardo** [wp-stream/stream#144]
After watching the video, I think it is cumbersome to reset all filters to zero.

I simple reset button that would reload the page without any filters might be the way to go.

![reset](https://f.cloud.github.com/assets/1933681/1823826/39a22840-7188-11e3-8d98-758b5d44c92a.png)

**Comment by fjarrett** [comment]
We have since significantly reduced the real estate of filtering so I'm resurrecting this issue. I think it's a good idea. Good on ya @jonathanbardo, thanks for your patience :smile:

**Comment by fjarrett** [comment]
Proposed UI

![screen shot 2015-02-04 at 12 27 43 am](https://cloud.githubusercontent.com/assets/522158/6036086/37001da0-ac05-11e4-92a7-9288f9e3feb6.png)
