### ISSUE TITLE
PHP Error accessing user in wp cli triggered update

### ISSUE THREAD

**Issue by NicktheGeek** [wp-stream/stream#1442]
# Bug Report

## Expected Behavior

The user object would be checked before attempting to use any fields or values.

## Actual Behavior

Get user is used to get a user, but `false` is returned because the user doesn't exist. This results in the error:
```
Warning: Attempt to read property "user login" on bool in /code/wp-content/plugins/stream/alerts/class-alert-type-ifttt.php on line 232
```

This may occur in other alerts, but this is the one currently triggering the problem. 

## Steps to Reproduce the Problem

1. trigger an alert where the user ID does not return a valid user
2. see the warning

## Screenshots

Drag and drop screenshots in this area that help illustrate the problem.

## System Information

This was noted when running a WPCLI command so the browser and OS are not applicable.

- Stream plugin version: 3.9.3
- WordPress version: 6.2.2
- PHP version: 8.0
- Browser: NA
- Computer operating system: NA

**Comment by delawski** [comment]
This should be fixed by #1494 in the [4.0.1 release](https://github.com/xwp/stream/releases/tag/v4.0.1).
