### ISSUE TITLE
PHP 8.1 Constant WP_Stream\FILTER_SANITIZE_STRING is deprecated

### ISSUE THREAD

**Issue by claytoncollie** [wp-stream/stream#1444]
# Bug Report

Noticed a deprecation notice in Query Monitor when running my site on PHP 8.1

`Constant WP_Stream\FILTER_SANITIZE_STRING is deprecated`

`wp-content/plugins/stream/classes/class-filter-input.php:100`

## System Information

- Stream plugin version: 3.9.3
- WordPress version: 6.2.2
- PHP version: 8.1.21
- Browser: Chrome
- Computer operating system: Mac

**Comment by gagan0123** [comment]
Any ETA on this, as the PR by @davefx seems to resolve the issue.
After migrating all the sites on the server to 8.1, error logs are now being filled with these two lines for all sites.

**Comment by ParhamG** [comment]
We are also running into this error on every request on PHP 8.1. This seems to have already been addressed in #1422 right before the last release (3.9.3) but it looks like it was only merged into the `develop` branch and not made it to the release? 

@kasparsd Will there be a new release soon including #1422 updates? PHP 8.0 EOL is coming up soon and it would be great if we can have a release including PHP 8.1 compatibility updates.

**Comment by benlk** [comment]
Also seen in PHP 8.2.
