### ISSUE TITLE
Create an SVN tag for each release on WordPress.org

### ISSUE THREAD

**Issue by westonruter** [wp-stream/stream#452]
We are only pushing the latest stable version to WordPress.org SVN. It would be useful for archiving purposes to also create an SVN tag for each release. This would facilitate installing old versions of WP-CLI, and it's a best practice I think to have the old versions up there.

**Comment by fjarrett** [comment]
This was implemented in the `wp-dev-lib` project's latest version of the `svn-push` script.

See https://github.com/xwp/wp-dev-lib/pull/54
