### ISSUE TITLE
Introduce WP-CLI stream command

### ISSUE THREAD

**Issue by westonruter** [wp-stream/stream#499]
It would be really cool if Stream data could be queried via WP-CLI, and if settings could be updated.

For example, there should be a `wp stream log` command that takes the filter arguments like `--author=1` or `--context=sidebars`.

Also, a cool use case would be something like `wp stream log --tail` which would output a continual stream of entries as they come in. The PHP process would keep running until `Ctrl-C`. Basically like Heartbeat on the command line. You could then pipe the results into something else.

**Comment by fjarrett** [comment]
I've created a [Query Reference](https://github.com/wp-stream/stream/wiki/Query-Reference) in our Wiki that can be used as a guide when using the WP-CLI command.

**Comment by fjarrett** [comment]
Released in `2.0.3`

**Comment by szepeviktor** [comment]
Could you please include the Query Ref. as PHP-doc?
E.g. https://github.com/wp-cli/wp-cli/blob/master/php/commands/post.php#L218-L278

**Comment by fjarrett** [comment]
Hi @szepeviktor, thanks for the suggestion.

Would you be willing to providing a pull request for this?

We have [Query Parameters documented](https://github.com/wp-stream/stream/wiki/Query-Reference) in the wiki. Otherwise we will just add these to the docblock when we get around to it.
