### ISSUE TITLE
RSS feed access

### ISSUE THREAD

**Issue by frankiejarrett** [wp-stream/stream#62]
There should be alternative access to Stream records via RSS. This will allow other applications to consume the data Stream is recording.

I think that every user should have their own secure key in order to access the feed:

```
http://mysite.com/?stream_rss_feed=iMGk3456B2x34L7vrD2uET18554n7rE4
```

This will ensure full compatibility with #59, so that if their Role's access has been denied from Stream, they will no longer be able to access the RSS feed. By having a unique key for each each it also allows restricting access on an individual user basis in the future.

This would need to appear in every user's profile that belongs to a role where access to Stream has been granted:

![screen shot 2013-12-12 at 10 16 38 am](https://f.cloud.github.com/assets/522158/1734598/cf78ff0e-6348-11e3-9441-5349a02820be.png)

**Comment by robertandrews** [comment]
I don't see "Private Feeds" on my Stream general settings page.
Nor is there a "Stream Feeds Key" option or RSS link on my profile page.

Have you removed this?

**Comment by lukecarbis** [comment]
Yes, it was removed about 6 months ago in Stream 3.0.
