### ISSUE TITLE
Same stream shows on all blogs in multisite

### ISSUE THREAD

**Issue by blobaugh** [wp-stream/stream#63]
When using WordPress Multisite the same stream content shows up for all blogs on the multisite. Other blog owners should not see the actions of other blogs.

This is a fairly simple fix. Add a blog_id column to the {prefix}_stream table. When inserting a new log entry in addition to storing the site_id (for multi-network installs) also store the specific blog id. 

Another boon to this is that a stream log viewer can easily be created in the network admin area to monitor the changes across the network.

**Comment by tharsheblows** [comment]
Support forum topic:
https://wordpress.org/support/topic/multsite-subsite-users-see-all-activity-across-main-site/
