### ISSUE TITLE
Clarify what "All activity is now stored only in the cloud..." actually means

### ISSUE THREAD

**Issue by jb510** [wp-stream/stream#665]
I'm still running 1.4.9 because I have no idea what they heck "All activity is now stored only in the cloud over SSL, local MySQL storage dependence is over!" in the change log, website and elsewhere actually means.  

What cloud?  My cloud? I have lots of clouds...  Your cloud?  How does that work?

Googling extensively and stopping just short of diff'ing all the code changes between 1.4.9 and 2.0.0 didn't result and any better idea what the heck that means.  From wp-stream.com: "Activity logs are stored securely in the cloud over SSL making your data immune to any intruder and making Stream the most robust WordPress audit trail solution on the web" doesn't help either...  

Many of us have pretty strict data protection policies to consider and while local MySQL storage was blowing up databases at least it was our own database that we owned and controlled and new the privacy policies of.

**Comment by quasel** [comment]
any idea when the option to self host the data storage will be available?

**Comment by fjarrett** [comment]
@quasel We are about to go into private beta with a few enterprise customers. I imagine there will be several months of feedback from them before we release it publicly.

**Comment by quasel** [comment]
@fjarrett thx for your quick replay looking forward to the release :+1:
