### ISSUE TITLE
PHP Catchable Fatal Error on EDD Checkout Page

### ISSUE THREAD

**Issue by desaiuditd** [wp-stream/stream#680]
WordPress SEO Connector is throwing PHP Catchable Fatal error on EDD checkout page. Hence Store is breaking.

![screenshot from 2015-01-07 16 52 51](https://cloud.githubusercontent.com/assets/2236554/5645039/7bbb8536-9690-11e4-9bb7-19f710c3d7f3.png)

Not really sure if we should remove `array` keyword from parameters in this function [here](https://github.com/wp-stream/stream/blob/develop/connectors/class-wp-stream-connector-wordpress-seo.php#L348) or not.

Submitting a PR as of now. Open to other suggestions or discussion

**Comment by fjarrett** [comment]
Thanks @desaiuditd! We will look into this issue further.
