### ISSUE TITLE
Search results ordered by relevance

### ISSUE THREAD

**Issue by lukecarbis** [wp-stream/stream#689]
Currently when searching Stream records, results are ordered by relevance.

For example, if I do a search for `Stream` I get:
![screen shot 2015-01-20 at 11 05 25](https://cloud.githubusercontent.com/assets/1097667/5810567/4559358e-a094-11e4-8f68-5c7ac1768cda.png)

In my opinion, it makes more sense to order them by date. Stream records are always presented by date except in this case and it confuses me.

**Comment by fjarrett** [comment]
I'd actually call this a bug. Thanks for pointing it out!
