### ISSUE TITLE
Release script

### ISSUE THREAD

**Issue by szepeviktor** [wp-stream/stream#703]
I can't stand the question: Do you plan to develop a release script including WP.org svn upload?

https://github.com/wp-stream/stream/commit/2e46ea783ddc6b26cd1490c3c7e4d715a2101f17#diff-a0b0b6220d7fc13d2d217348f422908c

**Comment by fjarrett** [comment]
@szepeviktor We are using [`wp-dev-lib`](https://github.com/xwp/wp-dev-lib) as a submodule which includes an [`svn-push`](https://github.com/xwp/wp-dev-lib/blob/master/svn-push) bash script, which we point to WP.org using the [`svn-url`](https://github.com/wp-stream/stream/blob/develop/svn-url) file in the project root.

We still bump versions manually in the codebase before running this script which then creates the release tag and pushes it to WP.org.

**Comment by szepeviktor** [comment]
So you are half way there.
