### ISSUE TITLE
No filter for wp-cli

### ISSUE THREAD

**Issue by szepeviktor** [wp-stream/stream#704]
As a wp-cli contributor I think there is no such thing as filters for wp-cli.
https://github.com/wp-stream/stream/blob/develop/includes/wp-cli.php#L41

May I create a PR to exclude that line and add YAML doc example?

```yaml
stream query:
    fields: created,ip,author,author_meta.user_login,author_role,summary
```

http://wp-cli.org/config/

**Comment by fjarrett** [comment]
@szepeviktor Interesting, there are several other community CLI commands that are using filters. Are there reasons why this should not be allowed?

https://github.com/hoppinger/advanced-custom-fields-wpcli/search?utf8=%E2%9C%93&q=apply_filters
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/blob/master/includes/class-edd-cli.php#L63

**Comment by szepeviktor** [comment]
How do you imagine to use it?

```php
wp stream query .... .... -require=path/to/hooks.php
```

**Comment by fjarrett** [comment]
@szepeviktor I see what you mean, a filter would be a global change not overridable from within the CLI. I like your idea of using YAML for this reason. Please go ahead!

**Comment by szepeviktor** [comment]
Looking at wp-cli.php it need some modification to be like other wp-cli commands.
I'll have lunch and show you my PR.

**Comment by fjarrett** [comment]
Sounds good, thanks @szepeviktor :smiley:

**Comment by szepeviktor** [comment]
@fjarrett How do you develop?? My site is called `subdir.wp` on my LAN.
And wp-stream.com complains about a system error.

**Comment by szepeviktor** [comment]
Now - suddenly - wp-stream.com let me in...

**Comment by fjarrett** [comment]
Hey @szepeviktor we develop in `wordpress-trunk.dev` on [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV). Not sure what trouble you were having without knowing the full error message.

**Comment by szepeviktor** [comment]
This is the proposed format. Basically making the hierarchy flat.
```php
array(4) {
  [0]=>
  array(11) {
    ["summary"]=>
    string(18) ""1" post published"
    ["author_meta.user_login"]=>
    string(6) "viktor"
    ["author_role"]=>
    string(13) "administrator"
    ["created"]=>
    string(28) "2015-02-25T18:07:20.709+0000"
    ["author"]=>
    int(1)
    ["ip"]=>
    string(14) "192.168.12.146"
    ["meta.links.self"]=>
    string(125) "https://api.wp-stream.com/sites/site-98b7bac0-bd18-11e4-952d-1b5d1e45d3ae/records/record-213c4eb0-bd19-11e4-952d-1b5d1e45d3ae"
    ["meta.links.collection"]=>
    string(81) "https://api.wp-stream.com/sites/site-98b7bac0-bd18-11e4-952d-1b5d1e45d3ae/records"
    ["meta.score"]=>
    NULL
    ["meta.sort"]=>
    int(1424887640709)
    ["ID"]=>
    string(43) "record-213c4eb0-bd19-11e4-952d-1b5d1e45d3ae"
  }
  [1]=>
  array(11) {
    ["summary"]=>
    string(16) ""1" post drafted"
    ["author_meta.user_login"]=>
    string(6) "viktor"
    ["author_role"]=>
    string(13) "administrator"
    ["created"]=>
    string(28) "2015-02-25T18:07:18.045+0000"
    ["author"]=>
    int(1)
    ["ip"]=>
    string(14) "192.168.12.146"
    ["meta.links.self"]=>
    string(125) "https://api.wp-stream.com/sites/site-98b7bac0-bd18-11e4-952d-1b5d1e45d3ae/records/record-1fabeab0-bd19-11e4-952d-1b5d1e45d3ae"
    ["meta.links.collection"]=>
    string(81) "https://api.wp-stream.com/sites/site-98b7bac0-bd18-11e4-952d-1b5d1e45d3ae/records"
```

**Comment by szepeviktor** [comment]
This is the documentation. I suggest to keep it outside the code.
```
Filtering fields is possible by configuring it in wp-cli.yml
```

```yaml
stream query:
  fields: created,ip,author,author_meta.user_login,author_role,summary
```

**Comment by szepeviktor** [comment]
https://github.com/wp-stream/stream/pull/705

**Comment by fjarrett** [comment]
Completed in https://github.com/wp-stream/stream/pull/705
