### ISSUE TITLE
Query without `created` field returns empty object

### ISSUE THREAD

**Issue by szepeviktor** [wp-stream/stream#706]
While fiddling with the wp-cli command I've found this returns an empty array.

```php
array (
  'fields' => 'summary,ID',
)
```

**Comment by fjarrett** [comment]
Hey @szepeviktor, I just tried the command and am not seeing this problem.

Anything else you could share that might help me reproduce it?

![screen shot 2015-04-02 at 2 44 00 pm](https://cloud.githubusercontent.com/assets/522158/6972003/6160ec6e-d946-11e4-8ded-93b19671867b.png)

**Comment by szepeviktor** [comment]
I was running the wp-cli way command: https://github.com/wp-stream/stream/pull/705

**Comment by szepeviktor** [comment]
That is why the PHP notation, not the CLI.

**Comment by fjarrett** [comment]
OK thanks, sorry that was not specified in the issue description.

**Comment by szepeviktor** [comment]
Yes. Sorry.

**Comment by szepeviktor** [comment]
I've ran the query in code.

**Comment by szepeviktor** [comment]
> While fiddling with the wp-cli command

**Comment by fjarrett** [comment]
@szepeviktor Have you tried `fields` as an array?

```php
array (
  'fields' => array( 'summary', 'ID' )
)
```

**Comment by szepeviktor** [comment]
It get converted to a string
`$query_args['fields'] = implode( ',', array_map( 'trim', $defaults ) );`
https://github.com/wp-stream/stream/blob/develop/includes/wp-cli.php#L43

**Comment by szepeviktor** [comment]
Do I think it is
```php
wp_stream_query( array( 'fields' => 'summary,ID' ) );
```

**Comment by fjarrett** [comment]
@szepeviktor The [Query Reference](https://github.com/wp-stream/stream/wiki/Query-Reference#fields) wiki says it's an array. But I wrote those docs :stuck_out_tongue:

**Comment by szepeviktor** [comment]
Sorry. It gets converted back to an array:
https://github.com/wp-stream/stream/blob/develop/includes/wp-cli.php#L53

**Comment by szepeviktor** [comment]
```php
wp_stream_query( array( 'fields' => array( 'summary', 'ID' ) ) );
```

**Comment by szepeviktor** [comment]
Could you run it?

**Comment by szepeviktor** [comment]
There is `created` in both docs example.

**Comment by fjarrett** [comment]
@szepeviktor Both of these work for me and return valid results:

```php
$records1 = wp_stream_query( array( 'fields' => array( 'summary', 'ID' ) ) );

$records2 = wp_stream_query( array( 'fields' => 'summary,ID' ) );
```

Because if the `fields` are not provided as an array they are [parsed by the `query` method](https://github.com/wp-stream/stream/blob/8955920469b4143802ce88069f256d1cf9de8ee5/classes/class-wp-stream-query.php#L118).

**Comment by fjarrett** [comment]
I can't reproduce this problem at all. If you can have some more detailed information about how/where you are calling this you may reopen.

**Comment by szepeviktor** [comment]
OK.
Right now I use Stream only on one shared-hosting production site.
